# Status bar colors
set-option -g status-style "fg=blue,bg=black"
set-option -g status-interval 5
set-option -g visual-activity on
set-window-option -g monitor-activity on

set -g default-terminal "screen-256color"

# Command prefix
set -g prefix C-a

# Start window indexing at one instead of zero
set -g base-index 1

unbind % # remove default binding since replacing
bind v split-window -h
bind h split-window -v
bind R source-file ~/.tmux.conf \; display-message "Config reloaded..."

# Panes
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind Left select-pane -L
bind Down select-pane -D
bind Up select-pane -U
bind Right select-pane -R
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize
bind -r H resize-pane -L 1
bind -r J resize-pane -D 1
bind -r K resize-pane -U 1
bind -r L resize-pane -R 1
bind -r S-Left resize-pane -L 1
bind -r S-Down resize-pane -D 1
bind -r S-Up resize-pane -U 1
bind -r S-Right resize-pane -R 1

# Resize by five cells
bind -r M-Left resize-pane -L 5
bind -r M-Down resize-pane -D 5
bind -r M-Up resize-pane -U 5
bind -r M-Right resize-pane -R 5

# Synchronize all panes in a window
bind y setw synchronize-panes

# Other ^A
unbind ^A
bind ^A last-window

# Lock server (^X)
unbind ^X
bind ^X lock-server

unbind " "
bind " " next-window
unbind n
bind n next-window

unbind ^P
bind ^P previous-window
unbind BSpace
bind BSpace previous-window

set-window-option -g xterm-keys on

# Status bar settings - adopted from tmuxline.vim and vim-airline
set -g status-justify "left"
set -g status on
set -g status-left-style "none"
set -g message-command-style "fg=colour144,bg=colour237"
set -g status-right-style "none"
set -g pane-active-border-style "fg=colour27"
set -g status-style "fg=default,bg=colour234"
set -g message-style "fg=colour144,bg=colour237"
set -g pane-border-style "fg=colour237"
set -g status-right-length 100
set -g status-left-length 100

set-window-option -g window-status-activity-style "fg=colour27,bg=colour234,none"
set-window-option -g window-status-separator ""
set-window-option -g window-status-style "fg=colour39,bg=colour234,none"

set -g status-left "#[fg=colour15,bg=colour27] #S #[fg=colour27,bg=colour234,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=colour237,bg=colour234]#[fg=colour146,bg=colour237] #(uptime | rev | cut -d':' -f1 | rev) #[fg=colour239,bg=colour237,nobold,nounderscore,noitalics]#[fg=colour152,bg=colour239] %d.%m.%Y  %H:%M #[fg=colour27,bg=colour239,nobold,nounderscore,noitalics]#[fg=colour15,bg=colour27] #h "
set-window-option -g window-status-format "#[fg=colour39,bg=colour234] #I #[fg=colour39,bg=colour234] #W "
set-window-option -g window-status-current-format "#[fg=colour234,bg=colour237,nobold,nounderscore,noitalics]#[fg=colour144,bg=colour237] #I #[fg=colour144,bg=colour237] #W #[fg=colour237,bg=colour234,nobold,nounderscore,noitalics]"
